/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EpisodesSlugRouteImport } from './routes/episodes_.$slug'
import { Route as AdminSuggestionsRouteImport } from './routes/admin.suggestions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminEpisodesRouteImport } from './routes/admin.episodes'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes_/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuggestionsRoute = AdminSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodesRoute = AdminEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/episodes': typeof EpisodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest': typeof SuggestRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/episodes': typeof EpisodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest': typeof SuggestRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/episodes': typeof EpisodesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggest': typeof SuggestRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/episodes_/$slug': typeof EpisodesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/auth'
    | '/episodes'
    | '/sitemap.xml'
    | '/suggest'
    | '/admin/episodes'
    | '/admin/messages'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/suggestions'
    | '/episodes/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/auth'
    | '/episodes'
    | '/sitemap.xml'
    | '/suggest'
    | '/admin/episodes'
    | '/admin/messages'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/suggestions'
    | '/episodes/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/auth'
    | '/episodes'
    | '/sitemap.xml'
    | '/suggest'
    | '/admin/episodes'
    | '/admin/messages'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/suggestions'
    | '/episodes_/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  EpisodesRoute: typeof EpisodesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuggestRoute: typeof SuggestRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/episodes_/$slug': {
      id: '/episodes_/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suggestions': {
      id: '/admin/suggestions'
      path: '/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AdminSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodes': {
      id: '/admin/episodes'
      path: '/episodes'
      fullPath: '/admin/episodes'
      preLoaderRoute: typeof AdminEpisodesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEpisodesRoute: typeof AdminEpisodesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuggestionsRoute: typeof AdminSuggestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEpisodesRoute: AdminEpisodesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuggestionsRoute: AdminSuggestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  EpisodesRoute: EpisodesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuggestRoute: SuggestRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
